import type { Translation } from './types';

export const translations: { [key: string]: Translation } = {
  en: {
    appName: "Receipt Book Pro",
    loginTitle: "Admin Login",
    username: "Username",
    password: "Password",
    login: "Login",
    logout: "Logout",
    loading: "Loading",
    invalidCredentials: "Invalid credentials. Please try again.",
    dashboard: "Dashboard",
    receipts: "Receipts",
    expenses: "Expenses",
    profileSettings: "Profile & Settings",
    languageSwitcher: "ગુજરાતી",
    // Setup
    setupTitle: "Welcome! Let's set up your account.",
    setupMethodPrompt: "Choose your login method:",
    setupWithPassword: "Create User ID & Password",
    setupWithPin: "Set up PIN Lock",
    createAccount: "Create Account",
    usernamePlaceholder: "Enter a username",
    passwordPlaceholder: "Enter a password",
    confirmPassword: "Confirm Password",
    passwordsDoNotMatch: "Passwords do not match.",
    pin: "PIN",
    setPin: "Set PIN",
    confirmPin: "Confirm PIN",
    pinPlaceholder: "Enter 4-digit PIN",
    pinsDoNotMatch: "PINs do not match.",
    pinLoginTitle: "Enter PIN",
    incorrectPin: "Incorrect PIN.",
    // Dashboard
    totalReceipts: "Total Receipts",
    totalExpenses: "Total Expenses",
    netBalance: "Net Balance",
    // Profile
    adminProfile: "Admin Profile",
    societyDetails: "Society Details",
    societyName: "Society Name",
    societyAddress: "Society Address",
    societyRegNo: "Society Reg. No.",
    adminName: "Admin Name",
    blockNumber: "Block Number",
    signature: "Signature",
    drawSignature: "Draw Signature",
    uploadSignature: "Upload Signature",
    clear: "Clear",
    saveProfile: "Save Profile",
    profileUpdated: "Profile updated successfully!",
    changePassword: "Change Password",
    changePin: "Change PIN",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    newPin: "New PIN",
    confirmNewPin: "Confirm New PIN",
    passwordUpdated: "Password updated successfully!",
    pinUpdated: "PIN updated successfully!",
    security: "Security",
    // Receipts
    receiptManagement: "Receipt Management",
    newReceipt: "New Receipt",
    searchReceipts: "Search by name, date, or receipt number...",
    exportAllPDF: "Export All (PDF)",
    exportAllExcel: "Export All (Excel)",
    receiptNumber: "Receipt No.",
    recipientName: "Recipient Name",
    date: "Date",
    maintenancePeriod: "Maintenance for",
    amount: "Amount",
    actions: "Actions",
    viewPDF: "View PDF",
    noReceipts: "No receipts found.",
    total: "Total",
    createReceipt: "Create Receipt",
    receiptCreated: "Receipt created successfully!",
    // PDF Header
    pdfHeader1: "Demo Apartment Division",
    pdfHeader2: "Co-op. Housing Service Society Ltd.",
    pdfHeader3: "Demo Address",
    pdfHeader4: "REG.NO Demo",
    // PDF Footer
    pdfFooter1: "This is only a digital soft copy.",
    pdfFooter2: "Created By",
    // Expense Calculator
    expenseCalculator: "Expense Calculator",
    itemName: "Item Name",
    operation: "Operation",
    addition: "Addition (+)",
    subtraction: "Subtraction (-)",
    addItem: "Add Item",
    grandTotal: "Grand Total",
    exportPDF: "Export (PDF)",
    saveReport: "Save Report",
    reportSaved: "Expense report saved!",
    expenseReport: "Expense Report",
    currentReportItems: "Current Report Items",
  },
  gu: {
    appName: "રસીદ બુક પ્રો",
    loginTitle: "એડમિન લોગિન",
    username: "વપરાશકર્તા નામ",
    password: "પાસવર્ડ",
    login: "લોગિન કરો",
    logout: "લોગઆઉટ",
    loading: "લોડ કરી રહ્યું છે",
    invalidCredentials: "અમાન્ય ઓળખપત્રો. કૃપા કરીને ફરી પ્રયાસ કરો.",
    dashboard: "ડેશબોર્ડ",
    receipts: "રસીદો",
    expenses: "ખર્ચ",
    profileSettings: "પ્રોફાઇલ અને સેટિંગ્સ",
    languageSwitcher: "हिन्दी",
    // Setup
    setupTitle: "આપનું સ્વાગત છે! ચાલો તમારું એકાઉન્ટ સેટ કરીએ.",
    setupMethodPrompt: "તમારી લોગિન પદ્ધતિ પસંદ કરો:",
    setupWithPassword: "વપરાશકર્તા ID અને પાસવર્ડ બનાવો",
    setupWithPin: "PIN લોક સેટ કરો",
    createAccount: "એકાઉન્ટ બનાવો",
    usernamePlaceholder: "વપરાશકર્તા નામ દાખલ કરો",
    passwordPlaceholder: "પાસવર્ડ દાખલ કરો",
    confirmPassword: "પાસવર્ડની પુષ્ટિ કરો",
    passwordsDoNotMatch: "પાસવર્ડ મેળ ખાતા નથી.",
    pin: "PIN",
    setPin: "PIN સેટ કરો",
    confirmPin: "PIN ની પુષ્ટિ કરો",
    pinPlaceholder: "૪-અંકનો PIN દાખલ કરો",
    pinsDoNotMatch: "PIN મેળ ખાતા નથી.",
    pinLoginTitle: "PIN દાખલ કરો",
    incorrectPin: "ખોટો PIN.",
    // Dashboard
    totalReceipts: "કુલ રસીદો",
    totalExpenses: "કુલ ખર્ચ",
    netBalance: "ચોખ્ખી સિલક",
    // Profile
    adminProfile: "એડમિન પ્રોફાઇલ",
    societyDetails: "સોસાયટીની વિગતો",
    societyName: "સોસાયટીનું નામ",
    societyAddress: "સોસાયટીનું સરનામું",
    societyRegNo: "સોસાયટી રજી. નંબર",
    adminName: "એડમિનનું નામ",
    blockNumber: "બ્લોક નંબર",
    signature: "સહી",
    drawSignature: "સહી દોરો",
    uploadSignature: "સહી અપલોડ કરો",
    clear: "સાફ કરો",
    saveProfile: "પ્રોફાઇલ સાચવો",
    profileUpdated: "પ્રોફાઇલ સફળતાપૂર્વક અપડેટ થઈ!",
    changePassword: "પાસવર્ડ બદલો",
    changePin: "PIN બદલો",
    newPassword: "નવો પાસવર્ડ",
    confirmNewPassword: "નવા પાસવર્ડની પુષ્ટિ કરો",
    newPin: "નવો PIN",
    confirmNewPin: "નવા PIN ની પુષ્ટિ કરો",
    passwordUpdated: "પાસવર્ડ સફળતાપૂર્વક અપડેટ થયો!",
    pinUpdated: "PIN સફળતાપૂર્વક અપડેટ થયો!",
    security: "સુરક્ષા",
    // Receipts
    receiptManagement: "રસીદ સંચાલન",
    newReceipt: "નવી રસીદ",
    searchReceipts: "નામ, તારીખ, અથવા રસીદ નંબર દ્વારા શોધો...",
    exportAllPDF: "બધા નિકાસ કરો (PDF)",
    exportAllExcel: "બધા નિકાસ કરો (Excel)",
    receiptNumber: "રસીદ નં.",
    recipientName: "પ્રાપ્તકર્તાનું નામ",
    date: "તારીખ",
    maintenancePeriod: "જાળવણી માટે",
    amount: "રકમ",
    actions: "ક્રિયાઓ",
    viewPDF: "PDF જુઓ",
    noReceipts: "કોઈ રસીદો મળી નથી.",
    total: "કુલ",
    createReceipt: "રસીદ બનાવો",
    receiptCreated: "રસીદ સફળતાપૂર્વક બનાવવામાં આવી!",
    // PDF Header
    pdfHeader1: "ડેમો એપાર્ટમેન્ટ વિભાગ",
    pdfHeader2: "કો.ઓપ. હાઉસિંગ સર્વિસ સોસાયટી લિ.",
    pdfHeader3: "ડેમો address",
    pdfHeader4: "REG.NO ડેમો",
    // PDF Footer
    pdfFooter1: "આ ફક્ત ડિજિટલ સોફ્ટ કોપી છે.",
    pdfFooter2: "દ્વારા બનાવેલ",
    // Expense Calculator
    expenseCalculator: "ખર્ચ કેલ્ક્યુલેટર",
    itemName: "વસ્તુનું નામ",
    operation: "ઓપરેશન",
    addition: "સરવાળો (+)",
    subtraction: "બાદબાકી (-)",
    addItem: "વસ્તુ ઉમેરો",
    grandTotal: "મહાન કુલ",
    exportPDF: "નિકાસ કરો (PDF)",
    saveReport: "રિપોર્ટ સાચવો",
    reportSaved: "ખર્ચનો રિપોર્ટ સાચવ્યો!",
    expenseReport: "ખર્ચ અહેવાલ",
    currentReportItems: "વર્તમાન રિપોર્ટ વસ્તુઓ",
  },
  hi: {
    appName: "रसीद बुक प्रो",
    loginTitle: "एडमिन लॉगिन",
    username: "उपयोगकर्ता नाम",
    password: "पासवर्ड",
    login: "लॉगिन करें",
    logout: "लॉगआउट",
    loading: "लोड हो रहा है",
    invalidCredentials: "अमान्य क्रेडेंशियल। कृपया पुन: प्रयास करें।",
    dashboard: "डैशबोर्ड",
    receipts: "रसीदें",
    expenses: "खर्च",
    profileSettings: "प्रोफ़ाइल और सेटिंग्स",
    languageSwitcher: "English",
    // Setup
    setupTitle: "आपका स्वागत है! चलिए आपका खाता सेट करते हैं।",
    setupMethodPrompt: "अपनी लॉगिन विधि चुनें:",
    setupWithPassword: "यूजर आईडी और पासवर्ड बनाएं",
    setupWithPin: "पिन लॉक सेट करें",
    createAccount: "खाता बनाएं",
    usernamePlaceholder: "एक उपयोगकर्ता नाम दर्ज करें",
    passwordPlaceholder: "पासवर्ड दर्ज करें",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    passwordsDoNotMatch: "पासवर्ड मेल नहीं खाते।",
    pin: "पिन",
    setPin: "पिन सेट करें",
    confirmPin: "पिन की पुष्टि करें",
    pinPlaceholder: "4-अंकीय पिन दर्ज करें",
    pinsDoNotMatch: "पिन मेल नहीं खाते।",
    pinLoginTitle: "पिन दर्ज करें",
    incorrectPin: "गलत पिन।",
    // Dashboard
    totalReceipts: "कुल प्राप्तियां",
    totalExpenses: "कुल खर्च",
    netBalance: "नेट बैलेंस",
    // Profile
    adminProfile: "एडमिन प्रोफ़ाइल",
    societyDetails: "सोसायटी विवरण",
    societyName: "सोसायटी का नाम",
    societyAddress: "सोसायटी का पता",
    societyRegNo: "सोसायटी पंजीकरण संख्या",
    adminName: "एडमिन का नाम",
    blockNumber: "ब्लॉक नंबर",
    signature: "हस्ताक्षर",
    drawSignature: "हस्ताक्षर बनाएं",
    uploadSignature: "हस्ताक्षर अपलोड करें",
    clear: "साफ़ करें",
    saveProfile: "प्रोफ़ाइल सहेजें",
    profileUpdated: "प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!",
    changePassword: "पासवर्ड बदलें",
    changePin: "पिन बदलें",
    newPassword: "नया पासवर्ड",
    confirmNewPassword: "नए पासवर्ड की पुष्टि करें",
    newPin: "नया पिन",
    confirmNewPin: "नए पिन की पुष्टि करें",
    passwordUpdated: "पासवर्ड सफलतापूर्वक अपडेट किया गया!",
    pinUpdated: "पिन सफलतापूर्वक अपडेट किया गया!",
    security: "सुरक्षा",
    // Receipts
    receiptManagement: "रसीद प्रबंधन",
    newReceipt: "नई रसीद",
    searchReceipts: "नाम, तारीख, या रसीद संख्या से खोजें...",
    exportAllPDF: "सभी निर्यात करें (PDF)",
    exportAllExcel: "सभी निर्यात करें (Excel)",
    receiptNumber: "रसीद संख्या",
    recipientName: "प्राप्तकर्ता का नाम",
    date: "तारीख",
    maintenancePeriod: "के लिए रखरखाव",
    amount: "राशि",
    actions: "कार्रवाई",
    viewPDF: "PDF देखें",
    noReceipts: "कोई रसीद नहीं मिली।",
    total: "कुल",
    createReceipt: "रसीद बनाएं",
    receiptCreated: "रसीद सफलतापूर्वक बनाई गई!",
    // PDF Header
    pdfHeader1: "डेमो अपार्टमेंट विभाग",
    pdfHeader2: "को.ऑप. हाउसिंग सर्विस सोसाइटी लि.",
    pdfHeader3: "डेमो पता",
    pdfHeader4: "REG.NO डेमो",
    // PDF Footer
    pdfFooter1: "यह केवल एक डिजिटल सॉफ्ट कॉपी है।",
    pdfFooter2: "द्वारा बनाया गया",
    // Expense Calculator
    expenseCalculator: "व्यय कैलकुलेटर",
    itemName: "आइटम का नाम",
    operation: "ऑपरेशन",
    addition: "जोड़ (+)",
    subtraction: "घटाव (-)",
    addItem: "आइटम जोड़ें",
    grandTotal: "कुल योग",
    exportPDF: "निर्यात (PDF)",
    saveReport: "रिपोर्ट सहेजें",
    reportSaved: "व्यय रिपोर्ट सहेजी गई!",
    expenseReport: "व्यय रिपोर्ट",
    currentReportItems: "वर्तमान रिपोर्ट आइटम",
  },
};